[package]
name = "sniffer"
version = "0.1.0"
authors = ["Mayank Shah <mayankshah1614@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
